"""add template position field to property model

Revision ID: 62e075a3acb4
Revises: 8ec871c109a9
Create Date: 2026-04-07 11:37:51.085505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62e075a3acb4'
down_revision: Union[str, Sequence[str], None] = '8ec871c109a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('template_position', sa.Integer(), server_default='4', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'template_position')
    # ### end Alembic commands ###
