"""add alert_creation_limit to company

Revision ID: 8ec871c109a9
Revises: 74ec76505951
Create Date: 2026-04-02 11:38:55.411967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ec871c109a9'
down_revision: Union[str, Sequence[str], None] = '74ec76505951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('alert_creation_limit', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'alert_creation_limit')
    # ### end Alembic commands ###
